export const portfolios = [
  {
    id: 1,
    name: "nlb",
    location: "Noida",
    image: "/images/nlb_noida/1.jpg",
    content: {
      id: 1,
      name: "nlb",
      location: "Noida",
      image: "/images/nlb_noida/1.jpg",
      description: "Images from nlb.",
      images: [
        "/images/nlb_noida/1.jpg",
        "/images/nlb_noida/10.jpg",
        "/images/nlb_noida/11.jpg",
        "/images/nlb_noida/12.jpg",
        "/images/nlb_noida/2.jpg",
        "/images/nlb_noida/3.jpg",
        "/images/nlb_noida/4.jpg",
        "/images/nlb_noida/5.jpg",
        "/images/nlb_noida/6.jpg",
        "/images/nlb_noida/7.jpg",
        "/images/nlb_noida/8.jpg",
        "/images/nlb_noida/9.jpg",
      ],
    },
  },

  {
    id: 3,
    name: "mtx",
    location: "Jaipur",
    image: "/images/mtx_jaipur_/1.jpg",
    content: {
      id: 3,
      name: "mtx",
      location: "Jaipur",
      image: "/images/mtx_jaipur_/1.jpg",
      description: "Images from mtx.",
      images: [
        "/images/mtx_jaipur_/1.jpg",
        "/images/mtx_jaipur_/10.jpg",
        "/images/mtx_jaipur_/11.jpg",
        "/images/mtx_jaipur_/12.jpg",
        "/images/mtx_jaipur_/13.jpg",
        "/images/mtx_jaipur_/14.jpg",
        "/images/mtx_jaipur_/15.jpg",
        "/images/mtx_jaipur_/16.jpg",
        "/images/mtx_jaipur_/17.jpg",
        "/images/mtx_jaipur_/18.jpg",
        "/images/mtx_jaipur_/19.jpg",
        "/images/mtx_jaipur_/2.jpg",
        "/images/mtx_jaipur_/20.jpg",
        "/images/mtx_jaipur_/21.jpg",
        "/images/mtx_jaipur_/22.JPG",
        "/images/mtx_jaipur_/23.jpg",
        "/images/mtx_jaipur_/24.jpg",
        "/images/mtx_jaipur_/25.jpg",
        "/images/mtx_jaipur_/26.jpg",
        "/images/mtx_jaipur_/27.jpg",
        "/images/mtx_jaipur_/28.jpg",
        "/images/mtx_jaipur_/29.JPG",
        "/images/mtx_jaipur_/3.jpg",
        "/images/mtx_jaipur_/30.png",
        "/images/mtx_jaipur_/4.jpg",
        "/images/mtx_jaipur_/5.jpg",
        "/images/mtx_jaipur_/6.jpg",
        "/images/mtx_jaipur_/7.jpg",
        "/images/mtx_jaipur_/8.jpg",
        "/images/mtx_jaipur_/9.jpg",
      ],
    },
  },
  {
    id: 4,
    name: "apj",
    location: "Gurgaon",
    image: "/images/apj_gurgaon/1.jpg",
    content: {
      id: 4,
      name: "apj",
      location: "Gurgaon",
      image: "/images/apj_gurgaon/1.jpg",
      description: "Images from apj.",
      images: [
        "/images/apj_gurgaon/1.jpg",
        "/images/apj_gurgaon/10.jpg",
        "/images/apj_gurgaon/11.jpg",
        "/images/apj_gurgaon/12.jpg",
        "/images/apj_gurgaon/13.jpg",
        "/images/apj_gurgaon/14.jpg",
        "/images/apj_gurgaon/15.jpg",
        "/images/apj_gurgaon/16.jpg",
        "/images/apj_gurgaon/2.jpg",
        "/images/apj_gurgaon/3.jpg",
        "/images/apj_gurgaon/4.jpg",
        "/images/apj_gurgaon/5.jpg",
        "/images/apj_gurgaon/6.jpg",
        "/images/apj_gurgaon/7.jpg",
        "/images/apj_gurgaon/8.jpg",
        "/images/apj_gurgaon/9.jpg",
      ],
    },
  },
  {
    id: 5,
    name: "cnx mt cafe",
    location: "Bangalore",
    image: "/images/cnx__bangalore_mt_cafe_/1.jpg",
    content: {
      id: 5,
      name: "cnx mt cafe",
      location: "Bangalore",
      image: "/images/cnx__bangalore_mt_cafe_/1.jpg",
      description: "Images from cnx mt cafe.",
      images: ["/images/cnx__bangalore_mt_cafe_/1.jpg"],
    },
  },
  {
    id: 6,
    name: "dalmia",
    location: "Lanka",
    image: "/images/dalmia_lanka/1.jpg",
    content: {
      id: 6,
      name: "dalmia",
      location: "Lanka",
      image: "/images/dalmia_lanka/1.jpg",
      description: "Images from dalmia.",
      images: [
        "/images/dalmia_lanka/1.jpg",
        "/images/dalmia_lanka/10.jpg",
        "/images/dalmia_lanka/11.jpg",
        "/images/dalmia_lanka/12.jpg",
        "/images/dalmia_lanka/13.jpg",
        "/images/dalmia_lanka/14.jpg",
        "/images/dalmia_lanka/15.jpg",
        "/images/dalmia_lanka/16.jpg",
        "/images/dalmia_lanka/17.jpg",
        "/images/dalmia_lanka/18.jpg",
        "/images/dalmia_lanka/19.jpg",
        "/images/dalmia_lanka/2.jpg",
        "/images/dalmia_lanka/20.jpg",
        "/images/dalmia_lanka/21.jpg",
        "/images/dalmia_lanka/22.jpg",
        "/images/dalmia_lanka/23.jpg",
        "/images/dalmia_lanka/24.jpg",
        "/images/dalmia_lanka/25.jpg",
        "/images/dalmia_lanka/26.jpg",
        "/images/dalmia_lanka/27.jpg",
        "/images/dalmia_lanka/28.jpg",
        "/images/dalmia_lanka/29.jpg",
        "/images/dalmia_lanka/3.jpg",
        "/images/dalmia_lanka/30.jpg",
        "/images/dalmia_lanka/31.jpg",
        "/images/dalmia_lanka/32.jpg",
        "/images/dalmia_lanka/33.jpg",
        "/images/dalmia_lanka/34.jpg",
        "/images/dalmia_lanka/35.jpg",
        "/images/dalmia_lanka/36.jpg",
        "/images/dalmia_lanka/37.jpg",
        "/images/dalmia_lanka/38.jpg",
        "/images/dalmia_lanka/39.jpg",
        "/images/dalmia_lanka/4.jpg",
        "/images/dalmia_lanka/40.jpg",
        "/images/dalmia_lanka/41.jpg",
        "/images/dalmia_lanka/42.jpg",
        "/images/dalmia_lanka/43.jpg",
        "/images/dalmia_lanka/44.jpg",
        "/images/dalmia_lanka/45.jpg",
        "/images/dalmia_lanka/46.jpg",
        "/images/dalmia_lanka/47.jpg",
        "/images/dalmia_lanka/48.jpg",
        "/images/dalmia_lanka/49.jpg",
        "/images/dalmia_lanka/5.jpg",
        "/images/dalmia_lanka/50.jpg",
        "/images/dalmia_lanka/51.jpg",
        "/images/dalmia_lanka/52.jpg",
        "/images/dalmia_lanka/53.jpg",
        "/images/dalmia_lanka/54.jpg",
        "/images/dalmia_lanka/55.jpg",
        "/images/dalmia_lanka/56.jpg",
        "/images/dalmia_lanka/57.jpg",
        "/images/dalmia_lanka/58.jpg",
        "/images/dalmia_lanka/59.jpg",
        "/images/dalmia_lanka/6.jpg",
        "/images/dalmia_lanka/60.jpg",
        "/images/dalmia_lanka/61.jpg",
        "/images/dalmia_lanka/62.jpg",
        "/images/dalmia_lanka/63.jpg",
        "/images/dalmia_lanka/64.jpg",
        "/images/dalmia_lanka/65.jpg",
        "/images/dalmia_lanka/66.jpg",
        "/images/dalmia_lanka/67.jpg",
        "/images/dalmia_lanka/68.jpg",
        "/images/dalmia_lanka/69.jpg",
        "/images/dalmia_lanka/7.jpg",
        "/images/dalmia_lanka/70.jpg",
        "/images/dalmia_lanka/71.jpg",
        "/images/dalmia_lanka/72.jpg",
        "/images/dalmia_lanka/8.jpg",
        "/images/dalmia_lanka/9.jpg",
      ],
    },
  },
  {
    id: 7,
    name: "heidelberg",
    location: "Cyberrgreen",
    image: "/images/heidelberg_cyberrgreen/1.jpg",
    content: {
      id: 7,
      name: "heidelberg",
      location: "Cyberrgreen",
      image: "/images/heidelberg_cyberrgreen/1.jpg",
      description: "Images from heidelberg.",
      images: [
        "/images/heidelberg_cyberrgreen/1.jpg",
        "/images/heidelberg_cyberrgreen/10.jpg",
        "/images/heidelberg_cyberrgreen/11.jpg",
        "/images/heidelberg_cyberrgreen/12.jpg",
        "/images/heidelberg_cyberrgreen/13.jpg",
        "/images/heidelberg_cyberrgreen/14.jpg",
        "/images/heidelberg_cyberrgreen/15.jpg",
        "/images/heidelberg_cyberrgreen/16.jpg",
        "/images/heidelberg_cyberrgreen/17.jpg",
        "/images/heidelberg_cyberrgreen/18.jpg",
        "/images/heidelberg_cyberrgreen/19.jpg",
        "/images/heidelberg_cyberrgreen/2.jpg",
        "/images/heidelberg_cyberrgreen/20.jpg",
        "/images/heidelberg_cyberrgreen/21.jpg",
        "/images/heidelberg_cyberrgreen/22.jpg",
        "/images/heidelberg_cyberrgreen/23.jpg",
        "/images/heidelberg_cyberrgreen/24.jpg",
        "/images/heidelberg_cyberrgreen/25.jpg",
        "/images/heidelberg_cyberrgreen/26.jpg",
        "/images/heidelberg_cyberrgreen/27.jpg",
        "/images/heidelberg_cyberrgreen/28.jpg",
        "/images/heidelberg_cyberrgreen/29.jpg",
        "/images/heidelberg_cyberrgreen/3.jpg",
        "/images/heidelberg_cyberrgreen/30.jpg",
        "/images/heidelberg_cyberrgreen/31.jpg",
        "/images/heidelberg_cyberrgreen/32.jpg",
        "/images/heidelberg_cyberrgreen/4.jpg",
        "/images/heidelberg_cyberrgreen/5.jpg",
        "/images/heidelberg_cyberrgreen/6.jpg",
        "/images/heidelberg_cyberrgreen/7.jpg",
        "/images/heidelberg_cyberrgreen/8.jpg",
        "/images/heidelberg_cyberrgreen/9.jpg",
      ],
    },
  },
  {
    id: 8,
    name: "emerson",
    location: "",
    image: "/images/emerson/1.jpg",
    content: {
      id: 8,
      name: "emerson",
      location: "",
      image: "/images/emerson/1.jpg",
      description: "Images from emerson.",
      images: ["/images/emerson/1.jpg", "/images/emerson/2.jpg"],
    },
  },

  {
    id: 10,
    name: "appirio",
    location: "Jaipur",
    image: "/images/appirio_jaipur_/1.jpg",
    content: {
      id: 10,
      name: "appirio",
      location: "Jaipur",
      image: "/images/appirio_jaipur_/1.jpg",
      description: "Images from appirio.",
      images: [
        "/images/appirio_jaipur_/1.jpg",
        "/images/appirio_jaipur_/2.jpg",
        "/images/appirio_jaipur_/3.jpg",
        "/images/appirio_jaipur_/4.jpg",
        "/images/appirio_jaipur_/5.jpg",
      ],
    },
  },
  {
    id: 11,
    name: "dalmia",
    location: "Cp",
    image: "/images/dalmia_cp/1.jpg",
    content: {
      id: 11,
      name: "dalmia",
      location: "Cp",
      image: "/images/dalmia_cp/1.jpg",
      description: "Images from dalmia.",
      images: [
        "/images/dalmia_cp/1.jpg",
        "/images/dalmia_cp/10.jpg",
        "/images/dalmia_cp/11.jpg",
        "/images/dalmia_cp/12.jpg",
        "/images/dalmia_cp/13.jpg",
        "/images/dalmia_cp/14.jpg",
        "/images/dalmia_cp/15.jpg",
        "/images/dalmia_cp/16.jpg",
        "/images/dalmia_cp/17.jpg",
        "/images/dalmia_cp/18.jpg",
        "/images/dalmia_cp/19.jpg",
        "/images/dalmia_cp/2.jpg",
        "/images/dalmia_cp/20.jpg",
        "/images/dalmia_cp/21.jpg",
        "/images/dalmia_cp/22.jpg",
        "/images/dalmia_cp/23.jpg",
        "/images/dalmia_cp/24.jpg",
        "/images/dalmia_cp/25.jpg",
        "/images/dalmia_cp/26.jpg",
        "/images/dalmia_cp/27.jpg",
        "/images/dalmia_cp/28.jpg",
        "/images/dalmia_cp/29.jpg",
        "/images/dalmia_cp/3.jpg",
        "/images/dalmia_cp/30.jpg",
        "/images/dalmia_cp/31.jpg",
        "/images/dalmia_cp/32.jpg",
        "/images/dalmia_cp/33.jpg",
        "/images/dalmia_cp/34.jpg",
        "/images/dalmia_cp/35.jpg",
        "/images/dalmia_cp/36.jpg",
        "/images/dalmia_cp/37.jpg",
        "/images/dalmia_cp/38.jpg",
        "/images/dalmia_cp/39.jpg",
        "/images/dalmia_cp/4.jpg",
        "/images/dalmia_cp/40.jpg",
        "/images/dalmia_cp/5.jpg",
        "/images/dalmia_cp/6.jpg",
        "/images/dalmia_cp/7.jpg",
        "/images/dalmia_cp/8.jpg",
        "/images/dalmia_cp/9.jpg",
      ],
    },
  },
  {
    id: 12,
    name: "cnx",
    location: "Vadodara",
    image: "/images/cnx_vadodara/1.jpg",
    content: {
      id: 12,
      name: "cnx",
      location: "Vadodara",
      image: "/images/cnx_vadodara/1.jpg",
      description: "Images from cnx.",
      images: [
        "/images/cnx_vadodara/1.jpg",
        "/images/cnx_vadodara/10.jpg",
        "/images/cnx_vadodara/11.jpg",
        "/images/cnx_vadodara/12.jpg",
        "/images/cnx_vadodara/13.jpg",
        "/images/cnx_vadodara/14.jpg",
        "/images/cnx_vadodara/15.jpg",
        "/images/cnx_vadodara/16.jpg",
        "/images/cnx_vadodara/17.jpg",
        "/images/cnx_vadodara/18.jpg",
        "/images/cnx_vadodara/19.jpg",
        "/images/cnx_vadodara/2.jpg",
        "/images/cnx_vadodara/20.jpg",
        "/images/cnx_vadodara/21.jpg",
        "/images/cnx_vadodara/22.jpg",
        "/images/cnx_vadodara/23.jpg",
        "/images/cnx_vadodara/24.jpg",
        "/images/cnx_vadodara/25.jpg",
        "/images/cnx_vadodara/26.jpg",
        "/images/cnx_vadodara/27.jpg",
        "/images/cnx_vadodara/28.jpg",
        "/images/cnx_vadodara/29.jpg",
        "/images/cnx_vadodara/3.jpg",
        "/images/cnx_vadodara/30.jpg",
        "/images/cnx_vadodara/31.jpg",
        "/images/cnx_vadodara/32.jpg",
        "/images/cnx_vadodara/33.jpg",
        "/images/cnx_vadodara/34.jpg",
        "/images/cnx_vadodara/35.jpg",
        "/images/cnx_vadodara/36.jpg",
        "/images/cnx_vadodara/37.jpg",
        "/images/cnx_vadodara/38.jpg",
        "/images/cnx_vadodara/39.jpg",
        "/images/cnx_vadodara/4.jpg",
        "/images/cnx_vadodara/40.jpg",
        "/images/cnx_vadodara/41.jpg",
        "/images/cnx_vadodara/42.jpg",
        "/images/cnx_vadodara/43.jpg",
        "/images/cnx_vadodara/44.jpg",
        "/images/cnx_vadodara/45.jpg",
        "/images/cnx_vadodara/46.jpg",
        "/images/cnx_vadodara/47.jpg",
        "/images/cnx_vadodara/48.jpg",
        "/images/cnx_vadodara/49.jpg",
        "/images/cnx_vadodara/5.jpg",
        "/images/cnx_vadodara/50.jpg",
        "/images/cnx_vadodara/51.jpg",
        "/images/cnx_vadodara/52.jpg",
        "/images/cnx_vadodara/53.mp4",
        "/images/cnx_vadodara/54.jpg",
        "/images/cnx_vadodara/55.jpg",
        "/images/cnx_vadodara/56.jpg",
        "/images/cnx_vadodara/57.jpg",
        "/images/cnx_vadodara/6.jpg",
        "/images/cnx_vadodara/7.jpg",
        "/images/cnx_vadodara/8.jpg",
        "/images/cnx_vadodara/9.jpg",
      ],
    },
  },
  

  {
    id: 15,
    name: "cnx cafe tpo",
    location: "Pune",
    image: "/images/cnx_pune_cafe_tpo/1.JPG",
    content: {
      id: 15,
      name: "cnx cafe tpo",
      location: "Pune",
      image: "/images/cnx_pune_cafe_tpo/1.JPG",
      description: "Images from cnx cafe tpo.",
      images: [
        "/images/cnx_pune_cafe_tpo/1.JPG",
        "/images/cnx_pune_cafe_tpo/2.JPG",
        "/images/cnx_pune_cafe_tpo/3.JPG",
        "/images/cnx_pune_cafe_tpo/4.JPG",
        "/images/cnx_pune_cafe_tpo/5.JPG",
        "/images/cnx_pune_cafe_tpo/6.JPG",
        "/images/cnx_pune_cafe_tpo/7.JPG",
        "/images/cnx_pune_cafe_tpo/8.JPG",
        "/images/cnx_pune_cafe_tpo/9.JPG",
      ],
    },
  },
  {
    id: 16,
    name: "cnx manus",
    location: "Mumbai",
    image: "/images/cnx_manus_mumbai/1.jpg",
    content: {
      id: 16,
      name: "cnx manus",
      location: "Mumbai",
      image: "/images/cnx_manus_mumbai/1.jpg",
      description: "Images from cnx manus.",
      images: [
        "/images/cnx_manus_mumbai/1.jpg",
        "/images/cnx_manus_mumbai/10.jpg",
        "/images/cnx_manus_mumbai/11.jpg",
        "/images/cnx_manus_mumbai/12.jpg",
        "/images/cnx_manus_mumbai/13.jpg",
        "/images/cnx_manus_mumbai/14.jpg",
        "/images/cnx_manus_mumbai/15.jpg",
        "/images/cnx_manus_mumbai/16.jpg",
        "/images/cnx_manus_mumbai/17.jpg",
        "/images/cnx_manus_mumbai/18.jpg",
        "/images/cnx_manus_mumbai/19.jpg",
        "/images/cnx_manus_mumbai/2.jpg",
        "/images/cnx_manus_mumbai/20.jpg",
        "/images/cnx_manus_mumbai/21.jpg",
        "/images/cnx_manus_mumbai/22.jpg",
        "/images/cnx_manus_mumbai/23.jpg",
        "/images/cnx_manus_mumbai/24.jpg",
        "/images/cnx_manus_mumbai/25.jpg",
        "/images/cnx_manus_mumbai/26.jpg",
        "/images/cnx_manus_mumbai/27.jpg",
        "/images/cnx_manus_mumbai/28.jpg",
        "/images/cnx_manus_mumbai/29.jpg",
        "/images/cnx_manus_mumbai/3.jpg",
        "/images/cnx_manus_mumbai/30.jpg",
        "/images/cnx_manus_mumbai/31.jpg",
        "/images/cnx_manus_mumbai/32.jpg",
        "/images/cnx_manus_mumbai/33.jpg",
        "/images/cnx_manus_mumbai/34.jpg",
        "/images/cnx_manus_mumbai/35.jpg",
        "/images/cnx_manus_mumbai/36.jpg",
        "/images/cnx_manus_mumbai/37.jpg",
        "/images/cnx_manus_mumbai/38.jpg",
        "/images/cnx_manus_mumbai/39.jpg",
        "/images/cnx_manus_mumbai/4.jpg",
        "/images/cnx_manus_mumbai/40.jpg",
        "/images/cnx_manus_mumbai/41.jpg",
        "/images/cnx_manus_mumbai/42.jpg",
        "/images/cnx_manus_mumbai/43.jpg",
        "/images/cnx_manus_mumbai/44.jpg",
        "/images/cnx_manus_mumbai/45.jpg",
        "/images/cnx_manus_mumbai/46.jpg",
        "/images/cnx_manus_mumbai/47.jpg",
        "/images/cnx_manus_mumbai/48.jpg",
        "/images/cnx_manus_mumbai/49.mp4",
        "/images/cnx_manus_mumbai/5.jpg",
        "/images/cnx_manus_mumbai/6.jpg",
        "/images/cnx_manus_mumbai/7.jpg",
        "/images/cnx_manus_mumbai/8.jpg",
        "/images/cnx_manus_mumbai/9.jpg",
      ],
    },
  },
  {
    id: 17,
    name: "boston",
    location: "Gurgaon",
    image: "/images/boston_gurgaon/1.jpg",
    content: {
      id: 17,
      name: "boston",
      location: "Gurgaon",
      image: "/images/boston_gurgaon/1.jpg",
      description: "Images from boston.",
      images: [
        "/images/boston_gurgaon/1.jpg",
        "/images/boston_gurgaon/10.mp4",
        "/images/boston_gurgaon/11.jpg",
        "/images/boston_gurgaon/12.jpg",
        "/images/boston_gurgaon/13.jpg",
        "/images/boston_gurgaon/14.jpg",
        "/images/boston_gurgaon/2.jpg",
        "/images/boston_gurgaon/3.jpg",
        "/images/boston_gurgaon/4.jpg",
        "/images/boston_gurgaon/5.jpg",
        "/images/boston_gurgaon/6.jpg",
        "/images/boston_gurgaon/7.jpg",
        "/images/boston_gurgaon/8.jpg",
        "/images/boston_gurgaon/9.jpg",
      ],
    },
  },

  {
    id: 19,
    name: "dalmia",
    location: "Noida",
    image: "/images/dalmia_noida/1.jpeg",
    content: {
      id: 19,
      name: "dalmia",
      location: "Noida",
      image: "/images/dalmia_noida/1.jpeg",
      description: "Images from dalmia.",
      images: [
        "/images/dalmia_noida/1.jpeg",
        "/images/dalmia_noida/10.jpeg",
        "/images/dalmia_noida/11.jpeg",
        "/images/dalmia_noida/12.jpeg",
        "/images/dalmia_noida/13.jpeg",
        "/images/dalmia_noida/14.jpeg",
        "/images/dalmia_noida/15.jpeg",
        "/images/dalmia_noida/16.jpeg",
        "/images/dalmia_noida/17.jpeg",
        "/images/dalmia_noida/18.jpeg",
        "/images/dalmia_noida/19.jpeg",
        "/images/dalmia_noida/2.jpeg",
        "/images/dalmia_noida/20.jpeg",
        "/images/dalmia_noida/21.jpeg",
        "/images/dalmia_noida/22.jpeg",
        "/images/dalmia_noida/3.jpeg",
        "/images/dalmia_noida/4.jpeg",
        "/images/dalmia_noida/5.jpeg",
        "/images/dalmia_noida/6.jpeg",
        "/images/dalmia_noida/7.jpeg",
        "/images/dalmia_noida/8.jpeg",
        "/images/dalmia_noida/9.jpeg",
      ],
    },
  },
  {
    id: 20,
    name: "cnx espace",
    location: "Pune",
    image: "/images/cnx_espace_pune_/1.jpg",
    content: {
      id: 20,
      name: "cnx espace",
      location: "Pune",
      image: "/images/cnx_espace_pune_/1.jpg",
      description: "Images from cnx espace.",
      images: [
        "/images/cnx_espace_pune_/1.jpg",
        "/images/cnx_espace_pune_/10.jpg",
        "/images/cnx_espace_pune_/11.jpg",
        "/images/cnx_espace_pune_/12.jpg",
        "/images/cnx_espace_pune_/13.jpg",
        "/images/cnx_espace_pune_/14.jpg",
        "/images/cnx_espace_pune_/15.jpg",
        "/images/cnx_espace_pune_/16.jpg",
        "/images/cnx_espace_pune_/17.jpg",
        "/images/cnx_espace_pune_/18.jpg",
        "/images/cnx_espace_pune_/19.jpg",
        "/images/cnx_espace_pune_/2.jpg",
        "/images/cnx_espace_pune_/20.jpg",
        "/images/cnx_espace_pune_/21.jpg",
        "/images/cnx_espace_pune_/22.jpg",
        "/images/cnx_espace_pune_/23.jpg",
        "/images/cnx_espace_pune_/24.jpg",
        "/images/cnx_espace_pune_/25.jpg",
        "/images/cnx_espace_pune_/26.jpg",
        "/images/cnx_espace_pune_/27.jpg",
        "/images/cnx_espace_pune_/28.jpg",
        "/images/cnx_espace_pune_/29.jpg",
        "/images/cnx_espace_pune_/3.jpg",
        "/images/cnx_espace_pune_/30.mp4",
        "/images/cnx_espace_pune_/31.jpg",
        "/images/cnx_espace_pune_/4.jpg",
        "/images/cnx_espace_pune_/5.jpg",
        "/images/cnx_espace_pune_/6.jpg",
        "/images/cnx_espace_pune_/7.jpg",
        "/images/cnx_espace_pune_/8.jpg",
        "/images/cnx_espace_pune_/9.jpg",
      ],
    },
  },
  {
    id: 21,
    name: "cnx wellness room",
    location: "",
    image: "/images/cnx_wellness_room_/1.jpg",
    content: {
      id: 21,
      name: "cnx wellness room",
      location: "",
      image: "/images/cnx_wellness_room_/1.jpg",
      description: "Images from cnx wellness room.",
      images: [
        "/images/cnx_wellness_room_/1.jpg",
        "/images/cnx_wellness_room_/10.jpg",
        "/images/cnx_wellness_room_/11.jpg",
        "/images/cnx_wellness_room_/12.jpg",
        "/images/cnx_wellness_room_/13.jpg",
        "/images/cnx_wellness_room_/14.jpg",
        "/images/cnx_wellness_room_/15.jpg",
        "/images/cnx_wellness_room_/16.jpg",
        "/images/cnx_wellness_room_/17.jpg",
        "/images/cnx_wellness_room_/18.jpg",
        "/images/cnx_wellness_room_/19.jpg",
        "/images/cnx_wellness_room_/2.jpg",
        "/images/cnx_wellness_room_/20.jpg",
        "/images/cnx_wellness_room_/21.jpg",
        "/images/cnx_wellness_room_/22.jpg",
        "/images/cnx_wellness_room_/23.jpg",
        "/images/cnx_wellness_room_/24.jpg",
        "/images/cnx_wellness_room_/25.jpg",
        "/images/cnx_wellness_room_/26.jpg",
        "/images/cnx_wellness_room_/27.jpg",
        "/images/cnx_wellness_room_/28.jpg",
        "/images/cnx_wellness_room_/29.jpg",
        "/images/cnx_wellness_room_/3.jpg",
        "/images/cnx_wellness_room_/30.jpg",
        "/images/cnx_wellness_room_/31.jpg",
        "/images/cnx_wellness_room_/32.jpg",
        "/images/cnx_wellness_room_/33.jpg",
        "/images/cnx_wellness_room_/34.jpg",
        "/images/cnx_wellness_room_/35.jpg",
        "/images/cnx_wellness_room_/36.jpg",
        "/images/cnx_wellness_room_/37.jpg",
        "/images/cnx_wellness_room_/38.jpg",
        "/images/cnx_wellness_room_/39.jpg",
        "/images/cnx_wellness_room_/4.jpg",
        "/images/cnx_wellness_room_/40.jpg",
        "/images/cnx_wellness_room_/41.jpg",
        "/images/cnx_wellness_room_/42.jpg",
        "/images/cnx_wellness_room_/43.jpg",
        "/images/cnx_wellness_room_/44.jpg",
        "/images/cnx_wellness_room_/45.jpg",
        "/images/cnx_wellness_room_/46.jpg",
        "/images/cnx_wellness_room_/47.jpg",
        "/images/cnx_wellness_room_/48.jpg",
        "/images/cnx_wellness_room_/49.jpg",
        "/images/cnx_wellness_room_/5.jpg",
        "/images/cnx_wellness_room_/50.jpg",
        "/images/cnx_wellness_room_/51.jpg",
        "/images/cnx_wellness_room_/52.jpg",
        "/images/cnx_wellness_room_/53.jpg",
        "/images/cnx_wellness_room_/54.jpg",
        "/images/cnx_wellness_room_/55.jpg",
        "/images/cnx_wellness_room_/56.jpg",
        "/images/cnx_wellness_room_/57.jpg",
        "/images/cnx_wellness_room_/58.jpg",
        "/images/cnx_wellness_room_/59.jpg",
        "/images/cnx_wellness_room_/6.jpg",
        "/images/cnx_wellness_room_/60.jpg",
        "/images/cnx_wellness_room_/61.jpg",
        "/images/cnx_wellness_room_/62.jpg",
        "/images/cnx_wellness_room_/63.jpg",
        "/images/cnx_wellness_room_/64.jpg",
        "/images/cnx_wellness_room_/65.jpg",
        "/images/cnx_wellness_room_/66.jpg",
        "/images/cnx_wellness_room_/67.jpg",
        "/images/cnx_wellness_room_/68.jpg",
        "/images/cnx_wellness_room_/7.jpg",
        "/images/cnx_wellness_room_/8.jpg",
        "/images/cnx_wellness_room_/9.jpg",
      ],
    },
  },
  {
    id: 22,
    name: "smart control",
    location: "",
    image: "/images/smart_control/1.jpg",
    content: {
      id: 22,
      name: "smart control",
      location: "",
      image: "/images/smart_control/1.jpg",
      description: "Images from smart control.",
      images: [
        "/images/smart_control/1.jpg",
        "/images/smart_control/10.jpg",
        "/images/smart_control/11.jpg",
        "/images/smart_control/12.jpg",
        "/images/smart_control/13.jpg",
        "/images/smart_control/14.jpg",
        "/images/smart_control/15.jpg",
        "/images/smart_control/16.jpg",
        "/images/smart_control/17.jpg",
        "/images/smart_control/18.jpg",
        "/images/smart_control/19.jpg",
        "/images/smart_control/2.jpg",
        "/images/smart_control/20.jpg",
        "/images/smart_control/21.jpg",
        "/images/smart_control/22.jpg",
        "/images/smart_control/23.jpg",
        "/images/smart_control/24.jpg",
        "/images/smart_control/25.jpg",
        "/images/smart_control/26.jpg",
        "/images/smart_control/27.jpg",
        "/images/smart_control/28.jpg",
        "/images/smart_control/29.jpg",
        "/images/smart_control/3.jpg",
        "/images/smart_control/30.jpg",
        "/images/smart_control/31.jpg",
        "/images/smart_control/32.jpg",
        "/images/smart_control/33.jpg",
        "/images/smart_control/34.jpg",
        "/images/smart_control/4.jpg",
        "/images/smart_control/5.jpg",
        "/images/smart_control/6.jpg",
        "/images/smart_control/7.jpg",
        "/images/smart_control/8.jpg",
        "/images/smart_control/9.jpg",
      ],
    },
  },
  {
    id: 23,
    name: "heidelberg",
    location: "Vatika",
    image: "/images/heidelberg__vatika/1.jpg",
    content: {
      id: 23,
      name: "heidelberg",
      location: "Vatika",
      image: "/images/heidelberg__vatika/1.jpg",
      description: "Images from heidelberg.",
      images: [
        "/images/heidelberg__vatika/1.jpg",
        "/images/heidelberg__vatika/10.jpg",
        "/images/heidelberg__vatika/11.jpg",
        "/images/heidelberg__vatika/12.jpg",
        "/images/heidelberg__vatika/13.jpg",
        "/images/heidelberg__vatika/14.jpg",
        "/images/heidelberg__vatika/15.jpg",
        "/images/heidelberg__vatika/16.jpg",
        "/images/heidelberg__vatika/17.jpg",
        "/images/heidelberg__vatika/18.jpg",
        "/images/heidelberg__vatika/19.jpg",
        "/images/heidelberg__vatika/2.jpg",
        "/images/heidelberg__vatika/20.jpg",
        "/images/heidelberg__vatika/21.jpg",
        "/images/heidelberg__vatika/22.jpg",
        "/images/heidelberg__vatika/23.jpg",
        "/images/heidelberg__vatika/24.jpg",
        "/images/heidelberg__vatika/25.jpg",
        "/images/heidelberg__vatika/26.jpg",
        "/images/heidelberg__vatika/27.jpg",
        "/images/heidelberg__vatika/28.jpg",
        "/images/heidelberg__vatika/29.jpg",
        "/images/heidelberg__vatika/3.jpg",
        "/images/heidelberg__vatika/30.jpg",
        "/images/heidelberg__vatika/31.jpg",
        "/images/heidelberg__vatika/32.jpg",
        "/images/heidelberg__vatika/33.jpg",
        "/images/heidelberg__vatika/34.jpg",
        "/images/heidelberg__vatika/35.jpg",
        "/images/heidelberg__vatika/36.jpg",
        "/images/heidelberg__vatika/37.jpg",
        "/images/heidelberg__vatika/4.jpg",
        "/images/heidelberg__vatika/5.jpg",
        "/images/heidelberg__vatika/6.jpg",
        "/images/heidelberg__vatika/7.jpg",
        "/images/heidelberg__vatika/8.jpg",
        "/images/heidelberg__vatika/9.jpg",
      ],
    },
  },
  {
    id: 24,
    name: "dalmia",
    location: "Assam",
    image: "/images/dalmia_assam/1.jpg",
    content: {
      id: 24,
      name: "dalmia",
      location: "Assam",
      image: "/images/dalmia_assam/1.jpg",
      description: "Images from dalmia.",
      images: [
        "/images/dalmia_assam/1.jpg",
        "/images/dalmia_assam/10.jpg",
        "/images/dalmia_assam/11.jpg",
        "/images/dalmia_assam/12.jpg",
        "/images/dalmia_assam/13.jpg",
        "/images/dalmia_assam/14.jpg",
        "/images/dalmia_assam/15.jpg",
        "/images/dalmia_assam/16.jpg",
        "/images/dalmia_assam/17.jpg",
        "/images/dalmia_assam/18.jpg",
        "/images/dalmia_assam/19.jpg",
        "/images/dalmia_assam/2.jpg",
        "/images/dalmia_assam/20.jpg",
        "/images/dalmia_assam/21.jpg",
        "/images/dalmia_assam/22.jpg",
        "/images/dalmia_assam/23.jpg",
        "/images/dalmia_assam/24.jpg",
        "/images/dalmia_assam/25.jpg",
        "/images/dalmia_assam/26.jpg",
        "/images/dalmia_assam/27.jpg",
        "/images/dalmia_assam/28.jpg",
        "/images/dalmia_assam/29.jpg",
        "/images/dalmia_assam/3.jpg",
        "/images/dalmia_assam/30.jpg",
        "/images/dalmia_assam/31.jpg",
        "/images/dalmia_assam/32.jpg",
        "/images/dalmia_assam/33.jpg",
        "/images/dalmia_assam/34.jpg",
        "/images/dalmia_assam/35.jpg",
        "/images/dalmia_assam/36.jpg",
        "/images/dalmia_assam/4.jpg",
        "/images/dalmia_assam/5.jpg",
        "/images/dalmia_assam/6.jpg",
        "/images/dalmia_assam/7.jpg",
        "/images/dalmia_assam/8.jpg",
        "/images/dalmia_assam/9.jpg",
      ],
    },
  },
];
